### Test Add New Private Prompt
POST {{base_url}}/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "content": "Private Prompt Content"
}
###

### Test List All Private Prompts
GET {{base_url}}/private/prompt/?skip=0&limit=10
Authorization: Basic {{basic_credential}}
###

### Test Delete a Private Prompt by GUID
DELETE {{base_url}}/private/prompt/81df98140c0a42eba39bc39148674c56
Authorization: Basic {{basic_credential}}
###

### Test Update a Private Prompt by GUID
PUT {{base_url}}/private/prompt/cc89ba398bc4488a8ad3f81737f936aa
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "content": "Updated Private Prompt Content 2",
  "classification": "private-classification",
  "tags": [
    "tag1",
    "tag2"
  ]
}
###

### Test List Private Prompts by Tag
GET {{base_url}}/private/prompt/tags/tag1
Authorization: Basic {{basic_credential}}
###

### Test List Private Prompts by Classification
GET {{base_url}}/private/prompt/classification/private-classification
Authorization: Basic {{basic_credential}}
###

