### Test Add New Public Prompt
POST http://{{base_url}}/public/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "content": "Sample Prompt Content {input_var} {output_var!}"
}

###

### Test List All Public Prompts
GET {{base_url}}/public/prompt/?skip=0&limit=10
###

### Test Delete a Public Prompt by GUID
DELETE {{base_url}}/public/prompt/5982cb445c774568bc254a90b3a7c5f7
Authorization: Basic {{basic_credential}}
###

### Test Update a Public Prompt by GUID
PUT {{base_url}}/public/prompt/823e8dc5c30e4ab48005badff96418cc
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "content": "Updated Prompt Content",
  "tags": ["tag1", "tag3"],
  "classification": "classification1"
}
###

### Test Retrieve a Public Prompt by GUID
GET {{base_url}}/public/prompt/823e8dc5c30e4ab48005badff96418cc
###

### Test Search Public Prompts
GET {{base_url}}/public/prompt/search/?query=Updated
###

### Test List Public Prompts by Tag
GET {{base_url}}/public/prompt/tags/
###

### Test List Public Prompts by Classification
GET {{base_url}}/public/prompt/classification                                                                                                                         /classification1
###

